FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY common/ ./common/
COPY api_gateway/ ./api_gateway/

ENV PYTHONPATH=/app
ENV PYTHONUNBUFFERED=1

CMD ["python", "api_gateway/main.py"]
